name: R2D2tagger
description: "Release Request Detection and Deployment"

inputs:
  changelog:
    description: "The changelog content (flattened)"
    required: true
  changelog-file:
    description: "Path to the changelog file"
    required: true
  github-token:
    description: "GitHub auth token with repo access"
    required: false
    default: ${{ github.token }}
  comsos-tags:
    description: "The historical tags starting from the PR merge commit sha"
    required: true
  r2d2-comment-only:
    description: "Whether the job should only comment on the PR instead of creating a tag (true/false)"
    required: false
    default: "false"

runs:
  using: docker
  image: ghcr.io/technicallyty/r2d2:latest
  env:
    COSMOS_CHANGELOG: ${{ inputs.changelog }}
    COSMOS_CHANGELOG_FILE: ${{ inputs.changelog-file }}
    COSMOS_TAGS: ${{ inputs.cosmos-tags }}
    COMMIT_SHA: ${{ github.event.pull_request.merge_commit_sha || github.sha }}
    GITHUB_TOKEN: ${{ inputs.github-token }}
    R2D2_PR_NUMBER: ${{ github.event.pull_request.number || github.ref_name }}
    R2D2_COMMENT_ONLY: ${{ inputs.r2d2-comment-only }}